stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building project..."
    - make build

test:
  stage: test
  script:
    - echo "Running tests..."
    - make test

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - make deploy
